---
# Refer https://github.com/syncthing/syncthing/blob/main/README-Docker.md
services:
  syncthing:
    image: syncthing/syncthing:2.0.12
    container_name: syncthing
    hostname: ${HOSTNAME}
    environment:
      - PUID=0  # due to podman's rootless uid mapping
      - PGID=0  # due to podman's rootless gid mapping
      - STGUIADDRESS=0.0.0.0:8384
    volumes:
      - ${PWD}/config:/var/syncthing/config:z
      - ${PWD}/data:/var/syncthing/data
      # - ${HOME}/media:/var/syncthing/media
    network_mode: host
    restart: unless-stopped
    healthcheck:
      test: curl -fkLsS -m 2 127.0.0.1:8384/rest/noauth/health | grep -o --color=never OK || exit 1
      interval: 1m
      timeout: 10s
      retries: 3
